# Generated by Django 4.1.2 on 2022-10-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Stock_availability',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_availability',
            field=models.BooleanField(null=True),
        ),
    ]
