# Generated by Django 4.1.2 on 2022-10-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_remove_product_stock_availability_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.CharField(default='mobile', max_length=50),
        ),
    ]
