# Generated by Django 4.1.2 on 2022-10-25 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0007_customer_order_things_alter_cart_created_at_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 4, 18, 29, 483583)),
        ),
    ]
