# Generated by Django 4.1.2 on 2022-10-25 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0010_orderitem_is_active_alter_cart_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='things',
            name='title',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 11, 5, 26, 142038)),
        ),
    ]
