# Generated by Django 4.1.1 on 2022-09-27 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamil', models.IntegerField()),
                ('english', models.IntegerField()),
                ('maths', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('img', models.ImageField(upload_to='images/')),
                ('marksheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Assignment.marksheet')),
            ],
        ),
        migrations.DeleteModel(
            name='mark',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
