# Generated by Django 4.1.1 on 2022-09-27 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0003_marksheet_science_marksheet_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='marksheet',
        ),
        migrations.AddField(
            model_name='marksheet',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Assignment.students'),
        ),
    ]
