# Generated by Django 4.1.1 on 2022-10-03 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0004_remove_students_marksheet_marksheet_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('mark', models.IntegerField(null=True)),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assignment.students')),
            ],
        ),
        migrations.DeleteModel(
            name='marksheet',
        ),
    ]
