# Generated by Django 4.1.1 on 2022-10-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0005_mark_delete_marksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='updated_time',
            field=models.DateTimeField(null=True),
        ),
    ]
