# Generated by Django 4.1.1 on 2022-10-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0006_students_created_time_students_updated_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rollno', models.IntegerField()),
                ('course', models.CharField(choices=[('1', 'Java'), ('2', 'Python'), ('3', 'Javascript')], max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.IntegerField(choices=[('1', 'Java'), ('2', 'Python'), ('3', 'Javascript')], null=True),
        ),
    ]
