# Generated by Django 4.1.1 on 2022-10-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0007_course_alter_mark_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='created_by',
            field=models.CharField(default='esther', max_length=50),
        ),
        migrations.AddField(
            model_name='students',
            name='modified_by',
            field=models.CharField(default='esther', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.CharField(choices=[('1', 'Java'), ('2', 'Python'), ('3', 'Javascript')], max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
