# Generated by Django 4.1.1 on 2022-10-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0009_author_book_publisher_alter_students_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='version',
            field=models.IntegerField(null=True),
        ),
    ]
