# Generated by Django 4.1.1 on 2022-10-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0010_publisher_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
